name: Release

on:
  push:
  pull_request:

jobs:
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 17
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git

